[package]
name = "clicks-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
crossbeam-channel = "0.5.15"
jack = "0.13.3"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
common = { path = "../common" }
chrono = "0.4.41"
