[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = [
 # "-C", "target-feature=+crt-static",
  "-C", "link-arg=--sysroot=/home/axel/git/clicks/dev",
  "-C", "linker-flavor=gcc",
  "-C", "link-args=-L/home/axel/git/clicks/dev/lib/aarch64-linux-gnu",
  "-A", "warnings"
]
